config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/cartao', to: 'pages#cartao'
  get '/perfil', to: 'pages#perfil', as: 'perfil'

  #TAG related routes
  get '/tag', to: 'pages#tag', as: 'tags_page_path'
  get '/tag_info', to: 'pages#tag_info'
  get '/tag_success', to: 'tags#tag_success'
  resources :tags, only: [ :index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'unlock', as: 'unlock'
      get 'temporary_lock', as: 'temporary_lock'
      get 'cancel', as: 'cancel'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  CATEGORIES = ['Posto', 'Estacionamento', 'Pedágio', 'Mercado']
  has_many :orders
  validates :category, :name, presence: true
  validates :category,  inclusion: { in: CATEGORIES }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :location
  belongs_to :tag

  validates :value, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :locations, through: :orders
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :tags
  has_many :orders, through: :tags

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :cpf, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :cpf, :photo, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :cpf, :photo, :address])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tag_total = tag_total_amount
    @card_amount = 730.50
    @discounts = 60.50
    @card_total = @card_amount + @tag_total - @discounts
    @limit = 4000
    @available = @limit - @card_total
  end

  def cartao
    @week_day = %w[DOM SEG TER QUAR QUI SEX SAB]
    @orders = current_user.orders
    @tags = current_user.tags
    @orders_hash = {}
    @orders.order('created_at DESC').each do |order|
      if @orders_hash[order.tag.nickname]
        if @orders_hash[order.tag.nickname]["#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}"]
          @orders_hash[order.tag.nickname]["#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}"] << order
        else
          @orders_hash[order.tag.nickname].merge!({ "#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}" => [order] })
        end
      else
        @orders_hash[order.tag.nickname] = { "#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}" => [order] }
      end
    end
    @tag_total_amount = tag_total_amount
    @card_total = 730.50 - 60.50 + @tag_total_amount
    @minimum_payment = @card_total * 0.15
  end

  def perfil
  end

  def tag_info
  end

  def tag
    @tags = Tag.where(user: current_user)
    if @tags.empty?
      redirect_to tag_info_path
    else
      redirect_to tags_path
    end
  end

  private

  def tag_total_amount
    orders = current_user.orders
    sum = 0
    if orders
      orders.each do |order|
        sum += order.value
      end
    end
    sum
  end
end

app/controllers/tags_controller.rb
require 'open-uri'

class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy unlock cancel temporary_lock]

  # GET /tags or /tags.json
  def index
    @tags = Tag.where(user: current_user)
  end

  # GET /tags/1 or /tags/1.json
  def show
    @tag = Tag.find(params[:id])
    @orders = @tag.orders
    @locations = @tag.locations
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window: render_to_string(partial: "map_info_window", locals: { location: location })
      }
    end
    @week_day = %w[DOM SEG TER QUAR QUI SEX SAB]
    @orders_hash = {}
    @orders.order('created_at DESC').each do |order|
      if @orders_hash["#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}"]
        @orders_hash["#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}"] << order
      else
        @orders_hash.merge!({ "#{@week_day[order.created_at.strftime('%w').to_i]}., #{order.created_at.strftime('%d/%m')}" => [order] })
      end
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new

    # fetch makers array
    makers_url = 'https://fipeapi.appspot.com/api/1/carros/marcas.json'
    serialized = URI.open(makers_url).read
    @makers_models_array =  []
    JSON.parse(serialized).each do |maker|
      @makers_models_array << "#{maker['id']}-#{maker['fipe_name']}"
    end
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user

    respond_to do |format|
      if @tag.save
        image_path = view_context.cl_image_path(@tag.photo.key)
        tag_hash = AwsTextExtractService.new.scan(image_path)

        @tag.update(
          plate: tag_hash["PLACA"],
          maker: tag_hash["MARCAMODELO/VERSÃO"],
          year: tag_hash["ANOMODELO"]
        )

        format.html { redirect_to edit_tag_path(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_success_path, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def tag_success
    @tags = current_user.tags
  end

  def unlock
    @tag.update(unlock_code: "xyz")
    toggle_locked
  end

  def temporary_lock
    toggle_locked
  end

  def cancel
    @tag.update(canceled: true)
    redirect_to tags_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def toggle_locked
      @tag.toggle!(:locked)
      redirect_to @tag
    end


    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:nickname, :plate, :maker, :model, :year, :locked, :user_id, :photo, :unlock_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_photo(user)
    if user.photo.attached?
      user.photo.key
    else
      "msrq1gzrlfh0qpuwjgoc.png"
    end
  end

  def highlight_home
    request.path == root_path ? 'active' : ''
  end

  def highlight_tab(tab)
    request.path.include?(tab) ? 'active' : ''
  end

  def show_notice
    'hide' if current_user.nil? || current_user.tags.length.nonzero?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarrefourTag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%# tags for PWA %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%# ------------- %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.6.0/cleave.min.js" integrity="sha512-KaIyHb30iXTXfGyI9cyKFUIRSSuekJt6/vqXtyQKhQP6ozZEGY8nOtRS6fExqE4+RbYHus2yGyYg1BrqxzV6YA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% render 'shared/flashes' %>
    <%= yield %>
    <div style="height: 65px"></div>
    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="greeting d-flex justify-content-between align-items-center">
  <%= cl_image_tag display_photo(current_user), aspect_ratio: 1, crop: :fill, class: "avatar" %>
  <div class="user-info flex-grow-1">
    <p class="name">Olá, <%= current_user.first_name %></p>
    <p class="credit-card-number">
    <span class="credit-card-block">
      <% 4.times do %>
        <i class="fas fa-circle"></i>
      <% end %>
    </span>
    <span class="credit-card-block">
      <% 4.times do %>
        <i class="fas fa-circle"></i>
      <% end %>
    </span>
    <span class="credit-card-block">
      <% 4.times do %>
        <i class="fas fa-circle"></i>
      <% end %>
    </span>
    3457
    </p>
  </div>
  <div class="notifications">
    <i class="far fa-bell notification-icon"></i>
    <div class="notification-count">98</div>
  </div>
</div>

<div class="balance">
  <div class="balance-info d-flex justify-content-between align-items-end">
    <div class="available-limit">
      <p>DISPONÍVEL</p>
      <h2>R$ <span><%= number_to_currency(@available, unit: "", separator: ",", delimiter: "." ).split(",").first %></span>,<%= number_to_currency(@available, unit: "R$", separator: "," ).split(',').last %></h2>
    </div>
    <p>AUMENTAR LIMITE <span><i class="fas fa-chevron-right chevron-right"></i></span></p>
  </div>
  <div class="limit">
    <div class="limit-bar"></div>
    <p class="limit-info">Limite Total R$ <span><%= @limit %>,</span>00</p>
  </div>
</div>

<div class="due-date-info d-flex justify-content-between">
  <div class="best-date d-flex align-items-center">
    <p>Melhor dia de compra</p>
    <h3>26 <span>JUN</span></h3>
  </div>
  <div class="due-date d-flex align-items-center">
    <p>Dia do vencimento</p>
    <h3>08 <span>JUL</span></h3>
  </div>
</div>

<% if current_user.tags.length.zero? %>
  <%= link_to tag_info_path do %>
    <div class="carrefour-tag d-flex justify-content-between align-items-center">
      <div class="tag-cta">
        <h3>Conheça o Carrefour TAG</h3>
        <p>Pagamento fácil e rápido</p>
      </div>
      <i class="fas fa-chevron-right chevron-right"></i>
    </div>
  <% end %>
<% end %>

<div class="credit-card-statement">
  <h3 class="border-bottom">Última Fatura</h3>
  <div class="statement-details">
    <div class="lancamentos-cartao d-flex justify-content-center">
      <p class="flex-shrink-0">Lançamentos da Fatura</p>
      <div class="dots">
        <p>...........................................................................................................................................................................................................................................................................................................................................................................................................................................................</p>
      </div>
      <p class="flex-shrink-0 value">R$ <span><%= number_to_currency(@card_amount, unit: "", separator: ",", delimiter: "." ).split(",").first %></span>,<%= number_to_currency(@card_amount, unit: "R$", separator: "," ).split(',').last %></p>
    </div>
    <div class="lancamentos-tag d-flex justify-content-center">
      <p class="flex-shrink-0">Lançamentos da TAG</p>
      <div class="dots">
        <p>...........................................................................................................................................................................................................................................................................................................................................................................................................................................................</p>
      </div>
      <p class="flex-shrink-0 value">R$ <span><%= number_to_currency(@tag_total, unit: "", separator: ",", delimiter: "." ).split(",").first %></span>,<%= number_to_currency(@tag_total, unit: "R$", separator: "," ).split(',').last %></p>
    </div>
    <div class="descontos d-flex justify-content-center">
      <p class="flex-shrink-0">Descontos</p>
      <div class="dots">
        <p>...........................................................................................................................................................................................................................................................................................................................................................................................................................................................</p>
      </div>
      <p class="flex-shrink-0 value">-R$ <span><%= number_to_currency(@discounts, unit: "", separator: ",", delimiter: "." ).split(",").first %></span>,<%= number_to_currency(@discounts, unit: "R$", separator: "," ).split(',').last %></p>
    </div>
    <div class="total-fatura d-flex justify-content-between border-top">
      <p class="flex-shrink-0">Total Fatura</p>
      <div class="dots">
        <p>...........................................................................................................................................................................................................................................................................................................................................................................................................................................................</p>
      </div>
      <p class="flex-shrink-0 value">R$ <span><%= number_to_currency(@card_total, unit: "", separator: ",", delimiter: "." ).split(",").first %></span>,<%= number_to_currency(@card_total, unit: "R$", separator: "," ).split(',').last %></p>
    </div>
  </div>
</div>

app/views/pages/perfil.html.erb
<div class="user-profile text-center">
  <%= cl_image_tag display_photo(current_user), aspect_ratio: 1, crop: :fill, class: "avatar-large" %>
  <h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
</div>

<div class="action-buttons d-flex flex-column text-center">
  <%= link_to edit_user_registration_path, class: "carrefour-button" do %>
    Edit Profile
  <% end %>

  <%= link_to destroy_user_session_path, method: :delete, class: "carrefour-button" do %>
    Log Out
  <% end %>
</div>

app/views/pages/tag_info.html.erb
<h2 style="margin: 1rem;"> Olá, <%= current_user.first_name %> </h2>


<div class="tag_info_banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= image_path 'carro_popular.png' %>)">
  <h1>Carrefour Tag</h1>
  <p>Solicite seu adesivo e aproveite as vantagens que o Carrefour TAG oferece!</p>
  <%= link_to "Peça agora!", new_tag_path, class: "new-tag-button" %>

</div>

<div class="vantagens_card">
  <div class="header">
    <h4>Vantagens</h4>
  </div>
  <div class="body">
    <ul>
      <div class="feature-item d-flex align-items-center">
        <div class="feature-icon">
          <i class="fas fa-car"></i>
        </div>
        <div>
          <li class="item-header">Cobertura Nacional</li>
          <li class="item-body">Aceita em Pedágios, Estacionamentos e Postos Carrefour por todo o Brasil *</li>
        </div>
      </div>
      <div class="feature-item d-flex align-items-center">
        <div class="feature-icon">
          <i class="fas fa-hand-holding-usd"></i>
        </div>
        <div>
          <li class="item-header"> Isenção de Mensalidade</li>
          <li class="item-body">Para quem abastece nos postos com bandeira Carrefour **</li>
        </div>
      </div>
      <div class="feature-item d-flex align-items-center">
        <div class="feature-icon" style="margin-right: 1.7rem;">
          <i class="fas fa-mobile-alt"></i>
        </div>
        <div>
          <li class="item-header"> Integrada a seu APP</li>
          <li class="item-body">Acompanhe sua utilização no seu APP do cartão Carrefour</li>
        </div>
      </div>
    </ul>
    <div class="ressalvas">
      <p>*Consulte os postos habilitados para pagamento com a TAG</p>
      <p>**Desconto progressivo para abastecimentos podendo chegar a zero para quem abastece acima de 500 reais no mês usando a TAG</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="low-navbar d-flex justify-content-around border-top">
  <%= link_to root_path do %>
    <div class="home text-center <%= highlight_home %>">
      <%= image_tag "menu_icons/home.svg" %>
      <p>Início</p>
    </div>
  <% end %>
  <%= link_to cartao_path do %>
    <div class="credit-card text-center <%= highlight_tab("cartao") %>">
      <%= image_tag "menu_icons/credit_card.svg" %>
      <p>Cartão</p>
    </div>
  <% end %>
  <div class="tag-notice <%= show_notice %>">
    NOVO
  </div>
  <%= link_to tags_path do %>
    <div class="tag text-center <%= highlight_tab("tag") %>">
      <%= image_tag "menu_icons/tag.svg" %>
      <p>Tag</p>
    </div>
  <% end %>
  <%= link_to perfil_path do %>
    <div class="profile text-center <%= highlight_tab("perfil") %>">
      <%= image_tag "menu_icons/profile.svg" %>
      <p>Perfil</p>
    </div>
  <% end %>
</div>

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/_map_info_window.html.erb
<h2><%= location.name %></h2>
<p><%= location.address %></p>

app/views/tags/edit.html.erb
<div class="edit-tag-message">
  <h2>Confira se os dados estão corretos.</h2>
</div>


<div class="form-container">
  <%= simple_form_for(@tag) do |f| %>
    <%= f.input :maker, collection: @makers_models_array, label: "Marca", label_html: { class: "new-tag-label" } %>
    <% if false %>
    <%= f.input :model, label: "Modelo", label_html: { class: "new-tag-label" }, input_html: { class: "select2"} %>
    <% end %>
    <%= f.input :plate, label: "Placa", label_html: { class: "new-tag-label" } %>
    <%= f.input :year, label: "Ano", label_html: { class: "new-tag-label" } %>
    <%= f.input :nickname, label: "Apelido do veículo", label_html: { class: "new-tag-label" } %>
    <%= f.submit "Confirmar", class: "carrefour-button" %>
  <% end %>
</div>

<script>
  const cleavePlate = new Cleave('#tag_plate', {
    delimiter: '-',
    blocks: [3, 4],
    uppercase: true
  });
  const cleaveYear = new Cleave('#tag_year', {
    blocks: [4],
    numericOnly: true,
    uppercase: true
  });
</script>

app/views/tags/index.html.erb
<h2 style="margin: 1rem;"> Olá, <%= current_user.first_name %> </h2>

<h4 style="margin: 1rem;">Veículos Cadastrados</h4>

<% if current_user.tags.length.zero? %>
  <p class="empty-question">Você não tem nenhuma TAG cadastrada. Gostaria de solicitar uma?</p>
<% else %>

  <% @tags.each_with_index do |tag, index| %>
    <% if !tag.canceled %>
      <%= link_to(tag) do %>
        <div class="tag_card">
          <div class="tag-title d-flex justify-content-between">
            <p><%= tag.nickname %></p>
            <i class="fas fa-chevron-right"></i>
          </div>
          <div class="tag_card_wrapper">
            <div class="car_info">
              <div class="info"><strong>Marca:</strong><span><%= tag.maker.split("/").first %></span></div>
              <div class="info"><strong>Modelo:</strong><span><%= tag.maker.split("/").last.slice!(/([a-zA-Z]+)/) %></span></div>
              <div class="info"><strong>Placa:</strong><span><%= tag.plate %></span></div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

<% end %>

<div style="padding-bottom: 65px;">
  <%= link_to 'Novo Veículo', new_tag_path, class: "new-tag-button new-vehicle" %>
</div>

app/views/tags/show.html.erb
<div id="map"
     style="width: 100%; height: 40vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class='card-padding my-4'>
  <h2 class='card-title text-center my-4'><%= @tag.nickname %></h2>
  
  <h2 class='card-title'>Lançamentos</h2>
  <hr>
  
  <% if @orders_hash.count > 0 %>
    <% @orders_hash.each do |date, orders| %>
      <p class='card-order-date'><%= date %></p>
      <% orders.each do |order| %>
        <div class='d-flex align-items-center justify-content-between card-detailed-transaction'>
          <div class='d-flex align-items-center justify-content-start'>
            <%= image_tag "order_icons/#{order.location.icon}.png" %>
            <div>
              <a class='text map-link' lat="<%= order.location.latitude %>" lng="<%= order.location.longitude %>"><%= order.location.name %></a>
              <p class='category'><%= order.location.category %></p>
            </div>
          </div>
          <p class='value'>R$ <span><%= order.value.to_s.split('.').first %></span>,<%= number_to_currency(order.value, unit: "R$", separator: "," ).split(',').last %></p>
        </div>  
      <% end %>
    <% end %>
  <% else %>
  <div class='card-detailed-transaction mb-4'>
    <p class='text'>Nenhum lançamento identificado...</p>
  </div>
  <% end %>
  

  <h2 class='card-title'>Opções</h2>
  <div class='my-3'>
  <hr>
  <%# Insert buttons here %>
    <% if (@tag.locked && @tag.unlock_code == "") %>
      <%# unlock button stuff %>
      <button id=<%="sweet-alert-unlock-tag"%> class="btn btn-outline-secondary carrefour-button" data-unlock=<%= @tag.unlock_code %> >Desbloquear</button>
      <%= link_to "", unlock_tag_path(@tag), id: "unlock-link", class: "hidden" %>
    <% elsif (@tag.unlock_code != "") %>
      <%# TEMPORARY LOCK %>
      <button id=<%="sweet-alert-temporary-lock-tag"%> class="btn btn-outline-secondary carrefour-button" data-unlock=<%= @tag.unlock_code %> ><%= @tag.locked ? 'Desbloquear' : 'Bloqueio temporário'%></button>
      <%= link_to "", temporary_lock_tag_path(@tag), id: "temporary-lock-link", class: "hidden" %>
    <% end %>
    <%# cancel button stuff %>
    <button class="btn btn-outline-secondary carrefour-button-red" id=<%="sweet-alert-cancel-tag"%>>Cancelar</button>
    <%= link_to "", cancel_tag_path(@tag), id: "cancel-link", class: "hidden" %>
  </div>
</div>

app/views/tags/tag_success.html.erb
<div class='tag-success'>
  <% if @tags.length < 2 %>
    <h2 class='mb-4'>PARABÉNS!</h2>
  <% else %>
    <h2 class='mb-4'>NOVO VEÍCULO CADASTRADO</h2>
  <% end %>
  <p>Estamos verificando tudo, mas, não se preocupe, sua TAG será enviada para o seu endereço cadastrado:</p>
  <p class='mb-2'><strong><%= current_user.address %></strong></p>
  <%= link_to 'Finalizar', tags_path, class: 'carrefour-button' %>
  <p class='mb-4 warning'>*caso o endereço não esteja correto, entre em contato com a nossa central de atendimento pelo 0800 718 2222</p>
</div>